In [2]:
import pandas as pd

# 출력 옵션 설정
pd.set_option('display.max_columns',None) # 모든 컬럼 출력
pd.set_option('display.width',1000) # 출력 너비 지정
pd.set_option('display.unicode.east_asian_with',True) # 한글 정렬 맞추기

# 공공데이터포털 사이트에서 다운로드 받은 bike02.csv파일 읽어오는 방법
df = pd.read_csv('greenData/bike02.csv',encoding='cp949')

In [3]:
# 01. 상위 10개 출력
df.head(10)

         대여일자    대여건수
0  2025-07-01  132914
1  2025-07-02  151653
2  2025-07-03  151092
3  2025-07-04  151367
4  2025-07-05  118354
5  2025-07-06  106785
6  2025-07-07  146664
7  2025-07-08  115371
8  2025-07-09  136307
9  2025-07-10  139733

In [4]:
# 02. 대여건수가 1000 이상인 데이터만 추출
df[df['대여건수'] >= 1000]

           대여일자    대여건수
0    2025-07-01  132914
1    2025-07-02  151653
2    2025-07-03  151092
3    2025-07-04  151367
4    2025-07-05  118354
..          ...     ...
179  2025-12-27   42381
180  2025-12-28   40774
181  2025-12-29   66652
182  2025-12-30   71026
183  2025-12-31   55570

[184 rows x 2 columns]

In [7]:
# 03. 대여건수기준내림차순정렬
df.sort_values(by='대여건수', ascending=False )

           대여일자    대여건수
87   2025-09-26  176011
93   2025-10-02  175022
84   2025-09-23  173588
91   2025-09-30  170957
92   2025-10-01  169645
..          ...     ...
98   2025-10-07   26673
43   2025-08-13   26358
165  2025-12-13   19152
101  2025-10-10   13940
97   2025-10-06   10493

[184 rows x 2 columns]

In [9]:
# 04. 전체 대여건수 합계 구하기
result = df['대여건수'].sum()
print(f"전체 대여건수 합계: {result}")

전체 대여건수 합계: 19647762

In [31]:
# 05. 평균 대여건수 구하기
result = df['대여건수'].mean()
print(f"평균 대여건수: {result:,.2f}")

평균 대여건수: 106,781.32

In [35]:
# 06. 가장 대여건수가 많은 날짜 찾기
result = df.sort_values(by='대여건수', ascending=False)
print(result.iloc[0]['대여일자'])
# print(result.index[0])
# print(f"가장 대여건수가 많은 날짜: {result.index[0]}")

2025-09-26

In [37]:
# 공공데이터포털 사이트에서 다운로드 받은 파일 읽어오는 방법
df = pd.read_csv('greenData/pm10.csv',encoding='cp949')
df

                      일시   구분  미세먼지(PM10)  초미세먼지(PM25)
0       2024-12-31 23:00   평균        24.0         12.0
1       2024-12-31 23:00  강남구        18.0         10.0
2       2024-12-31 23:00  강동구        28.0         14.0
3       2024-12-31 23:00  강북구        16.0          9.0
4       2024-12-31 23:00  강서구        25.0         12.0
...                  ...  ...         ...          ...
228378   2024-01-01 0:00  용산구        35.0         25.0
228379   2024-01-01 0:00  은평구        21.0         15.0
228380   2024-01-01 0:00  종로구        28.0         26.0
228381   2024-01-01 0:00   중구        26.0         26.0
228382   2024-01-01 0:00  중랑구        28.0         23.0

[228383 rows x 4 columns]

In [60]:
# 구분 컬럼의 데이터 중'평균'인 행을 제외하여 실제 자치구 데이터만 남깁니다. (데이터전처리)
data = df[df['구분'] != '평균']
# 미세먼지(PM10) 농도가 25 이상이면서 동시에 초미세먼지(PM25) 농도가 15 이상인 '주의 요망' 지역 찾기
# 다중 조건 줄 때 and : &, or : **, not : ~
data02 = (data['미세먼지(PM10)'] >= 25) & (data['초미세먼지(PM25)'] >= 15)
data03 = data[data02]
result = data03[['구분','미세먼지(PM10)','초미세먼지(PM25)']]
print(result)

          구분  미세먼지(PM10)  초미세먼지(PM25)
5        관악구        25.0         17.0
9        노원구        28.0         16.0
14      서대문구        31.0         16.0
15       서초구        31.0         15.0
19       양천구        25.0         15.0
...      ...         ...          ...
228377  영등포구        32.0         26.0
228378   용산구        35.0         25.0
228380   종로구        28.0         26.0
228381    중구        26.0         26.0
228382   중랑구        28.0         23.0

[100203 rows x 3 columns]

In [61]:
# from datetime import datetime (import시 그냥 datetime만 작성)

# 공공데이터포털 사이트에서 다운로드 받은 파일 읽어오는 방법
df = pd.read_csv('greenData/accident.csv',encoding='cp949')
df

       사고년도        사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인
0     2022년  2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만
1     2022년  2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음
2     2022년  2022-01-02  13:35    남해선   125.0  부산   0   2    과속
3     2022년  2022-01-02  15:10    남해선   104.0  순천   0   2    기타
4     2022년  2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만
...     ...         ...    ...    ...     ...  ..  ..  ..   ...
4706  2024년  2024-12-29   5:55   서해안선   312.9  목포   0   1    기타
4707  2024년  2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속
4708  2024년  2024-12-29  22:18    영동선    18.1  인천   0   0    기타
4709  2024년  2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타
4710  2024년  2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만

[4711 rows x 9 columns]

In [90]:
# pandas에서 날짜를 추출하는 함수 종류
# CSV에 입력된 날짜는 문자열 데이터 타입
# ★ 날짜형식으로 형변환하는 함수 : datetime()

# 사고일자 컬럼을 datetime 형식으로 변환하고, 이를 활용하여'사고월'이라는 새로운 파생변수(컬럼)를 생성
# 사고일자가 날짜형식으로 변경됨
df['사고일자'] = pd.to_datetime(df['사고일자'])
df

       사고년도       사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인  사고월  사상자수
0     2022년 2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만    1     0
1     2022년 2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음    1     0
2     2022년 2022-01-02  13:35    남해선   125.0  부산   0   2    과속    1     2
3     2022년 2022-01-02  15:10    남해선   104.0  순천   0   2    기타    1     2
4     2022년 2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만    1     0
...     ...        ...    ...    ...     ...  ..  ..  ..   ...  ...   ...
4706  2024년 2024-12-29   5:55   서해안선   312.9  목포   0   1    기타   12     1
4707  2024년 2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속   12     1
4708  2024년 2024-12-29  22:18    영동선    18.1  인천   0   0    기타   12     0
4709  2024년 2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타   12     0
4710  2024년 2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만   12     1

[4711 rows x 11 columns]

In [ ]:
# 문제) 사고일자 컬럼을 datetime 형식으로 변환하고, 이를 활용하여'사고월'이라는 새로운 파생변수(컬럼)를 생성

# (1)사고일자의 월을 출력 : dt.month(월), dt.year(년), dt.day(일), dt.hour(시), dt.minute(분), dt.second(초)
# (2) dt.dayofweek : 요일을 숫자로 반환(0:월요일 ~ 6:일요일)
# (3) dt.day_name() : 요일 이름이 문자열('Monday')
# (4) dt.quarter : 분기(1분기 ~ 4분기)
df['사고월'] = df['사고일자'].dt.month
df

In [ ]:
# 문제) 월별 사고 건수를 집계하여 어느 월에 사고가 가장 많이 발생했는지 확인하세요.
# groupby().count() => 데이터가 비어있지 않은 값의 개수를 셈
# groupby().size() => 그룹별 전체 행의 개수를 셈 (비어있는 값의 개수도 셈)
monthCount = df.groupby('사고월').size()
# idxmax() => 가장 큰 값이 들어있는 위치(인덱스 이름)에 접근하여 가져옴 -> 가장 큰 값의 인덱스를 가져옴★
maxMonth = monthCount.idxmax()
print(monthCount)
print(f"가장 많이 발생한 월: {maxMonth}월")

In [88]:
# 문제) 사망자수와 부상자수를 더하여 '사상자수'라는 파생변수를 생성하세요
df['사상자수'] = df['사망'] + df['부상']
df

       사고년도       사고일자   사고시각    노선명  사고발생이정  방향  사망  부상    원인  사고월  사상자수
0     2022년 2022-01-01  16:25    중앙선   145.2  부산   0   0  주시태만    1     0
1     2022년 2022-01-01  17:15  부산포항선    73.1  부산   0   0    졸음    1     0
2     2022년 2022-01-02  13:35    남해선   125.0  부산   0   2    과속    1     2
3     2022년 2022-01-02  15:10    남해선   104.0  순천   0   2    기타    1     2
4     2022년 2022-01-03   0:35    경부선   329.9  부산   0   0  주시태만    1     0
...     ...        ...    ...    ...     ...  ..  ..  ..   ...  ...   ...
4706  2024년 2024-12-29   5:55   서해안선   312.9  목포   0   1    기타   12     1
4707  2024년 2024-12-29   9:48  익산장수선     8.0  완주   0   1    과속   12     1
4708  2024년 2024-12-29  22:18    영동선    18.1  인천   0   0    기타   12     0
4709  2024년 2024-12-31  15:28  청주영덕선    62.7  상주   0   0    기타   12     0
4710  2024년 2024-12-31  19:34  무안광주선     4.7  무안   1   0  주시태만   12     1

[4711 rows x 11 columns]

In [95]:
result = df.groupby('노선명')['사상자수'].sum().sort_values(ascending=False).head(5)
print(result)

노선명
경부선      620
중부선      293
중부내륙선    279
영동선      274
서해안선     274
Name: 사상자수, dtype: int64

In [94]:
result02 = len(df[(df['원인'] == '졸음') & (df['사망'] >= 1)])
print(result02)

88