In [4]:
from bs4 import BeautifulSoup
# 파일 읽기
with open('greenData/member_data.xml','r',encoding='utf-8-sig') as f:
    # 파싱
    soup = BeautifulSoup(f,'xml')

# 데이터 추출(select 모두 출력 : 내가 지정한 'member'(반드시 태그)안의 모든 것
members = soup.select('member')

for m in members :
    name = m.select_one('name').text
    age = m.select_one('age').text
    city = m.select_one('city').text
    print(f"이름:{name}, 나이:{age}, 도시:{city}")

이름:김철수, 나이:25, 도시:서울
이름:이영희, 나이:30, 도시:부산
이름:박민수, 나이:22, 도시:대전

In [8]:
# json.loads() : JSON형식의 문자열을 파이썬 사전(Dict)으로 변환
# json.dumps() : 파이썬 사전(Dict)데이터를 Json 문자열로 변환
# (*만약 json에러 출력된다면 import)

# JSON 문자열 -> 사전 (Decoding)
json_str = '{"name":"Alice","role":"admin","level":5}'
data = json.loads(json_str)
print(data['name'], type(data))

# 사전 -> JSON 문자열 (Encoding)
user = {"id":7, "status":"online"}
userjson = json.dumps(user,indent=4) # indent는 들여쓰기 4칸 하겠다.
print(userjson)

Alice <class 'dict'>
{
    "id": 7,
    "status": "online"
}

In [18]:
# pandas란 : 테이블형 데이터를 다룰 수 있는 다양한 기능을 가진 라이브러리
# raw data : 아직 데이터 분석을 위해 정제되지 않은 기본데이터를 의미함
# pandas는 반드시 import해서 사용
# 데이터를 다루는 방식 2가지
# -> 시리즈(series)는 1차원 (행하나 또는 열 하나)
# -> 데이터프레임(Dataframe)은 2차원(테이블형) 데이터

import pandas as pd # 라이브러리 import(대부분 pd로 사용) -> pd.판다스 함수 형태로 호출하여 사용
# ★ index는 행의 레이블(=제목)을 의미
# index를 지정 X -> 0부터 시작하는 인덱스 자동 생성
# index를 지정 O -> 지정된 index로 사용
seriesdata = pd.Series([70,80,90], index=['국어','영어','수학']) # 튜플
seriesdata
seriesdata.index # Index(['국어', '영어', '수학'], dtype='object') 
 # - index 변경
seriesdata.index = ['미술','과학','사회']
seriesdata
#  - Series 삭제 : del seriesdata['미술']
del seriesdata['미술']
seriesdata

과학    80
사회    90
dtype: int64

In [23]:
# < pandas 데이터 타입 >
# object : str 또는 혼용 데이터 타입(문자열)
# int64 : 파이썬의 int(정수)
# float64 : 파이썬의 float(부동소수점)
# bool : 파이썬의 bool 또는 boolean(True/False)
# datetime : 날짜/시간
# timedelta : 두개의 datetime64간의 차이

# 01. 문자
seriesdata = pd.Series(['dave','alex','amir']) # dtype: object
seriesdata

# 02. 정수
seriesdata = pd.Series([1,2,3]) # dtype: int64
seriesdata

# 03. int64의 정수를 float64 부동소수점으로 변경 명령어 : Series.astype(변경할 타입)
seriesdata.astype('float') # 1.0 / 2.0 / 3.0

# 04. 섞여있을때
seriresdata = pd.Series(['dave',1,2,3]) # dtype: object
seriresdata

# 05. boolean
seriresdata = pd.Series([True,False,True]) # dtype: bool
seriresdata

0     True
1    False
2     True
dtype: bool

In [60]:
# 데이터프레임(DataFrame) : 2차원 테이블형태의 데이터이며, 데이터 분석/머신 러닝에서 데이터 처리를 위해 주로 사용
# 행(row)과 열(column)로 구성
# 행의 레이블은 인덱스로, 열의 레이블은 컬럼이라 명칭

df = pd.DataFrame({
    "년도":[2000, 2012, 2013],
    "미국":[2.1, 2.2, 2.3],
    "한국":[0.4, 0.5, 0.45],
    "중국":[10, 13, 15]
},
# index = [2001, 2002, 2003]
)
# df
# df.index # Index([2001, 2002, 2003], dtype='int64')
# df.columns # Index(['미국', '한국', '중국'], dtype='object')

# # 데이터프레임의 열을 수정
# # df.columns = {'일본','프랑스','독일'}
# df
# df.values # [ 2.1 ,  0.4 , 10.  ] [ 2.2 ,  0.5 , 13.  ] [ 2.3 ,  0.45, 15.  ]

# # df.set_index(값)
df = df.set_index('년도')
# df.index.name='연도'
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2012  2.2  0.50  13
2013  2.3  0.45  15

In [64]:
# 데이터프레임 데이터 접근하기
# df.loc : index를 통해서 값을 찾음
# df.iloc : 인덱스 번호를 통해서 값을 찾음(0부터 시작)
df.loc[2000] # index라는 데이터프레임의 레이블을 이용해 값 출력
df.iloc[1] # 이미 가지고있는 0부터 시작하는 index로 값 출력
# 한국의 index가 2000인 데이터만 추출
print(df['한국'][2000]) # 특정한 key값의 데이터를 추출

# 데이터프레임의 컬럼(=열) 삭제 : del
# del df['미국']
# df
# 데이터프레임의 인덱스(=행) 삭제 : drop([인덱스이름])
df.drop([2012])

0.4

       미국    한국  중국
년도
2000  2.1  0.40  10
2013  2.3  0.45  15

In [68]:
import pandas as pd

data = {
    '대여소' : ['강남', '강남', '홍대', '홍대', '잠실', '잠실'],
    '이용자수' : [120, 150, 80, 90, 200, 180],
    '대여시간' : [30, 45, 20, 25, 60, 55],
    '이용일자' : ['2024-01-01', '2024-01-02', '2024-01-01', '2024-01-02', '2024-01-01', '2024-01-02']
}

df = pd.DataFrame(data)
df.head(3)
df

  대여소  이용자수  대여시간        이용일자
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
2  홍대    80    20  2024-01-01
3  홍대    90    25  2024-01-02
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02

In [69]:
# 02. Data자료를 이용해 이용자수가 100명 이상인 데이터만 출력하시오
df[df['이용자수'] >= 100]

  대여소  이용자수  대여시간        이용일자
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02

In [71]:
# 03. Data자료를 이용해 대여시간 기준으로 오름차순 정렬하여 출력하시오.
# df.sort_values(by='price') : 기본값은 오름차순 정렬
df.sort_values(by='대여시간')

# df.sort_values(by='price', ascending=False) : 내림차순 정렬
df.sort_values(by='대여시간', ascending=False)

  대여소  이용자수  대여시간        이용일자
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02
1  강남   150    45  2024-01-02
0  강남   120    30  2024-01-01
3  홍대    90    25  2024-01-02
2  홍대    80    20  2024-01-01

In [72]:
# 04. Data자료를 이용해 "총이용량" 컬럼을 이용자수 * 대여시간으로 계산하여 추가하시오.
df['총이용량'] = df['이용자수'] * df['대여시간']
df

  대여소  이용자수  대여시간        이용일자   총이용량
0  강남   120    30  2024-01-01   3600
1  강남   150    45  2024-01-02   6750
2  홍대    80    20  2024-01-01   1600
3  홍대    90    25  2024-01-02   2250
4  잠실   200    60  2024-01-01  12000
5  잠실   180    55  2024-01-02   9900

In [78]:
# 05. Data자료를 이용해 컬대여소별 총 이용자수 구하여 출력하시오.
#     대여소별 이용자수를 내림차순하여 출력
# df.groupby('대여소')['이용자수'].sum()
df.groupby('대여소')['이용자수'].sum().sort_values(ascending=False)

대여소
잠실    380
강남    270
홍대    170
Name: 이용자수, dtype: int64

In [79]:
# 06. Data자료를 이용해 이용자수가 100 이상인 데이터만 추출하여 대여소별 평균대여시간 구하여 출력하시오.
df[df['이용자수'] >= 100].groupby('대여소')['대여시간'].mean()

대여소
강남    37.5
잠실    57.5
Name: 대여시간, dtype: float64

In [80]:
# 07. Data자료를 이용해 대여소별 "총이용량" 합계 구하기
df['총이용량'] = df['이용자수'] * df['대여시간']
df.groupby('대여소')['총이용량'].sum()

대여소
강남    10350
잠실    21900
홍대     3850
Name: 총이용량, dtype: int64

In [99]:
# 08. 가장 바쁜 날짜 찾기. => 이용일자별 이용자 수 합계가 가장 많은 날짜 출력
busy = df.groupby('이용일자')['이용자수'].sum().sort_values(ascending=False)
print(busy)
print(f"가장 바쁜 날짜: {busy.index[0]}")

이용일자
2024-01-02    420
2024-01-01    400
Name: 이용자수, dtype: int64
가장 바쁜 날짜: 2024-01-02

In [104]:
# 09. 이용자수 평균이 가장 높은 대여소 찾기.
high = df.groupby('대여소')['이용자수'].mean().sort_values(ascending=False)
print(high)
print(f"평균 이용자수 가장 높은 대여소: {high.index[0]}")

대여소
잠실    190.0
강남    135.0
홍대     85.0
Name: 이용자수, dtype: float64
평균 이용자수 가장 높은 대여소: 잠실